### ISSUE TITLE
Functional test case reconf.test_stress_sticky.SchedSticky fails

### ISSUE THREAD

**Issue by avbelov23** [tempesta-tech/tempesta#1152]
Random tests fail from a case `reconf.test_stress_sticky.SchedSticky`. Sometimes can all pass

**Comment by avbelov23** [comment]
```
Running functional tests...
----------------------------------------------------------------------

test_ratio_add_srvs (reconf.test_stress_sticky.SchedSticky) ... ERROR
test_ratio_del_add_srvs (reconf.test_stress_sticky.SchedSticky) ... ok
test_ratio_del_srvs (reconf.test_stress_sticky.SchedSticky) ... ok

======================================================================
ERROR: test_ratio_add_srvs (reconf.test_stress_sticky.SchedSticky)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/avb/Projects/tempesta-test/reconf/reconf_stress.py", line 100, in tearDown
    stress.StressTest.tearDown(self)
  File "/home/avb/Projects/tempesta-test/testers/stress.py", line 104, in tearDown
    raise Exception("Errors happened during test on Tempesta")
Exception: Errors happened during test on Tempesta

----------------------------------------------------------------------
Ran 3 tests in 36.476s

FAILED (errors=1)
```

**Comment by avbelov23** [comment]
```
[11448.712983] Start test: reconf.test_stress_sticky.SchedSticky.test_ratio_add_srvs
[11449.078351] [tdb] Start Tempesta DB
[11449.095926] net_ratelimit: 1618 callbacks suppressed
[11449.095926] [tempesta fw] Initializing Tempesta FW kernel module...
[11449.095940] [tempesta fw] Registering new classifier: frang
[11449.098725] [tempesta fw] Registering new scheduler: hash
[11449.098727] [tempesta fw] Registering new scheduler: ratio
[11449.114833] [tempesta fw] Preparing for the configuration processing.
[11449.114935] [tempesta fw] Configuration processing is completed.
[11449.123399] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff942bdac00000
[11449.128190] [tempesta fw] Open listen socket on: 0.0.0.0
[11449.128217] [tempesta fw] modules are started
[11454.602208] [tempesta fw] Live reconfiguration of Tempesta.
[11454.602216] [tempesta fw] Preparing for the configuration processing.
[11454.602386] [tempesta fw] Configuration processing is completed.
[11454.603234] [tempesta fw] ERROR: sticky sched: pinned server 127.0.0.1:8003 in group 'default' is down
[11454.603237] [tempesta fw] Warning: request dropped: processing error, status 502: 127.0.0.1
[11454.603313] [tempesta fw] ERROR: sticky sched: pinned server 127.0.0.1:8003 in group 'default' is down
[11454.603315] [tempesta fw] Warning: request dropped: processing error, status 502: 127.0.0.1
[11454.603345] [tempesta fw] ERROR: sticky sched: pinned server 127.0.0.1:8003 in group 'default' is down
[11454.603347] [tempesta fw] Warning: request dropped: processing error, status 502: 127.0.0.1
[11454.603373] [tempesta fw] ERROR: sticky sched: pinned server 127.0.0.1:8003 in group 'default' is down
[11459.292325] [tdb] Close table 'filter0.tdb'
[11459.305433] [tdb] Shutdown Tempesta DB
[11459.494337] End test:   reconf.test_stress_sticky.SchedSticky.test_ratio_add_srvs
```

**Comment by ikoveshnikov** [comment]
I was convinced that the issue is only related to tests stability and Tempesta code has no issues:
- there are a lot of function tests for sticky sessions
- the issue happen on developer PC and never happened in CI environment.

But there are two reasons for the test to fail. First is tests instability as I was thinking at the beginning. The issue is related to tempesta-tech/tempesta-test#71 . When the VMs in tests are overloaded the userspace processes can't process events, like connections reopening, fast enough. CI has more resources, so the issue never reproduced there.

The second reason is related to #940 issue. It has absolutely the same behaviour.

So I move the issue to next release, until all the related issues are solved.

**Comment by ikoveshnikov** [comment]
#940 issue is definitely has an effect on this tests, and we can possibly hold on a requests that comes during server group reconfiguration and reduce generated 502 errors. But this 502 errors doesn't really effect the test outcome. Some 502 errors are allowed, it's just strictly checked that the servers wasn't down more that 1 second which is maximum allowed reconfiguration downtime timeout.

The real issue for the test failure was the incorrect logging levels in sticky cookie module and I've lost the point. The more details in the tempesta-tech/tempesta-test#127 review comment.
