### ISSUE TITLE
Sporadic failures on several functional tests

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1475]
The test fails sporadically. On current master as of 737113eabd593ee082bb1a0016196ee02eee5534
```
# ./run_tests.py sched.test_per_group_lb.RedefineGlobalSched.test_inheritLoading disabled file
....

----------------------------------------------------------------------
Running functional tests (resuming from after sched.test_per_group_lb.RedefineGlobalSched.test_inherit)...
----------------------------------------------------------------------


----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

# ./run_tests.py sched.test_per_group_lb.RedefineGlobalSched.test_inherit
...........

----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------

test_inherit (sched.test_per_group_lb.RedefineGlobalSched) ... 	Init test case...
	Starting Nginx on nginx_8001
	Starting Nginx on nginx_8000
	Starting Nginx on nginx_8003
	Starting Nginx on nginx_8002
	Starting Nginx on nginx_8005
	Starting Nginx on nginx_8004
	Starting Nginx on nginx_8007
	Starting Nginx on nginx_8006
	Starting Nginx on nginx_8009
	Starting Nginx on nginx_8008
	Starting TempestaFW on localhost
Running client
Running client
	Client exit
	Client exit
Server group custom uses 'ratio dynamic' scheduler
FAIL
	Teardown
Stopping client
	client stdout:
Running 10s test @ http://127.0.0.1:80/
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.68ms   10.80ms  60.08ms   56.65%
    Req/Sec     2.40k    90.40     2.60k    90.50%
  47807 requests in 10.07s, 11.81MB read
Requests/sec:   4747.35
Transfer/sec:      1.17MB
---- RESULTS --------
Status 200 : 47807 times
---- END ------------

Client is stopped
Stopping client
	client stdout:
Running 10s test @ http://127.0.0.1:80/
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    75.65ms   33.03ms 399.77ms   92.70%
    Req/Sec   680.57     60.64   777.00     93.00%
  13561 requests in 10.05s, 3.35MB read
Requests/sec:   1349.85
Transfer/sec:    341.42KB
---- RESULTS --------
Status 200 : 13561 times
---- END ------------

Client is stopped
	Stopping TempestaFW on localhost
	Stopping Nginx on nginx_8001
	Removing Nginx config for nginx_8001
	Stopping Nginx on nginx_8000
	Removing Nginx config for nginx_8000
	Stopping Nginx on nginx_8003
	Removing Nginx config for nginx_8003
	Stopping Nginx on nginx_8002
	Removing Nginx config for nginx_8002
	Stopping Nginx on nginx_8005
	Removing Nginx config for nginx_8005
	Stopping Nginx on nginx_8004
	Removing Nginx config for nginx_8004
	Stopping Nginx on nginx_8007
	Removing Nginx config for nginx_8007
	Stopping Nginx on nginx_8006
	Removing Nginx config for nginx_8006
	Stopping Nginx on nginx_8009
	Removing Nginx config for nginx_8009
	Stopping Nginx on nginx_8008
	Removing Nginx config for nginx_8008
Not started
Removing interfaces

======================================================================
FAIL: test_inherit (sched.test_per_group_lb.RedefineGlobalSched)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 321, in test_inherit
    self.check_lb(group, lb_type)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 303, in check_lb
    self.check_dynamic_lb(group, group_name)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 272, in check_dynamic_lb
    % (prev_name, name))
AssertionError: Faster server nginx_8005 got less weight than slower nginx_8006

----------------------------------------------------------------------
Ran 1 test in 11.973s

FAILED (failures=1)
````
And several following tries also fail.

The reason for the failures is unclear, so need to investigate whether the problem is in the test itself or in Tempesta FW.

**Comment by krizhanovsky** [comment]
Just ran the full test quite `./run_tests.py -n` as of 82ab0ad8281b39d78a95a1450716683e2f86d70e on 2 CPU VM and got the same error and may other failed tests (I used the kernel of version 515de2a8e08b5db2772851464bddaad7c6367d36:
```
======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.AddingBackendNewSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 255, in test
    self.pre_test()
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 227, in pre_test
    server.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/helpers/control.py", line 445, in run_start
    err_msg=(self.err_msg % ('start', self.get_name())))
  File "/root/tempesta-test/helpers/remote.py", line 96, in run_cmd
    (err_msg, stdout, stderr))
Exception: Remote error: Can't start Nginx on 192.168.10.1:16384, stdout = , stderr = None

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.AddingBackendNewSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 158, in tearDown
    raise excpt
Exception: Error during stopping servers

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.ChangingSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 314, in test
    self.pre_test()
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 227, in pre_test
    server.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/helpers/control.py", line 445, in run_start
    err_msg=(self.err_msg % ('start', self.get_name())))
  File "/root/tempesta-test/helpers/remote.py", line 96, in run_cmd
    (err_msg, stdout, stderr))
Exception: Remote error: Can't start Nginx on 192.168.10.1:16384, stdout = , stderr = None

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.ChangingSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 158, in tearDown
    raise excpt
Exception: Error during stopping servers

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.DontModifyBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 248, in test
    self.pre_test()
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 227, in pre_test
    server.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/helpers/control.py", line 445, in run_start
    err_msg=(self.err_msg % ('start', self.get_name())))
  File "/root/tempesta-test/helpers/remote.py", line 96, in run_cmd
    (err_msg, stdout, stderr))
Exception: Remote error: Can't start Nginx on 192.168.10.1:16384, stdout = , stderr = None

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.DontModifyBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 158, in tearDown
    raise excpt
Exception: Error during stopping servers

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.RemovingBackendSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 286, in test
    self.pre_test()
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 227, in pre_test
    server.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/helpers/control.py", line 445, in run_start
    err_msg=(self.err_msg % ('start', self.get_name())))
  File "/root/tempesta-test/helpers/remote.py", line 96, in run_cmd
    (err_msg, stdout, stderr))
Exception: Remote error: Can't start Nginx on 192.168.10.1:16384, stdout = , stderr = None

======================================================================
ERROR: test (very_many_backends.test_deadtime_1M.RemovingBackendSG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/very_many_backends/test_deadtime_1M.py", line 158, in tearDown
    raise excpt
Exception: Error during stopping servers

======================================================================
ERROR: test (frang.test_http_resp_code_block.HttpRespCodeBlock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/frang/test_http_resp_code_block.py", line 131, in test
    deproxy_cl.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/framework/deproxy_client.py", line 169, in run_start
    BaseDeproxyClient.run_start(self)
  File "/root/tempesta-test/framework/deproxy_client.py", line 65, in run_start
    raise e
error: [Errno 99] Cannot assign requested address

======================================================================
ERROR: test (frang.test_http_resp_code_block.HttpRespCodeBlockWithReply)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/frang/test_http_resp_code_block.py", line 194, in test
    deproxy_cl.start()
  File "/root/tempesta-test/helpers/stateful.py", line 36, in start
    self.run_start()
  File "/root/tempesta-test/framework/deproxy_client.py", line 169, in run_start
    BaseDeproxyClient.run_start(self)
  File "/root/tempesta-test/framework/deproxy_client.py", line 65, in run_start
    raise e
error: [Errno 99] Cannot assign requested address

======================================================================
FAIL: test (h2.test_h2_headers.CurlTestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/h2/test_h2_headers.py", line 135, in test
    (curl.returncode)))
AssertionError: Curl return code is not 0 (1).

======================================================================
FAIL: test_inherit (sched.test_per_group_lb.LateRedefineGlobalSched)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 321, in test_inherit
    self.check_lb(group, lb_type)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 303, in check_lb
    self.check_dynamic_lb(group, group_name)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 272, in check_dynamic_lb
    % (prev_name, name))
AssertionError: Faster server nginx_8005 got less weight than slower nginx_8006

======================================================================
FAIL: test_inherit (sched.test_per_group_lb.RedefineAllScheds)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 321, in test_inherit
    self.check_lb(group, lb_type)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 303, in check_lb
    self.check_dynamic_lb(group, group_name)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 272, in check_dynamic_lb
    % (prev_name, name))
AssertionError: Faster server nginx_8005 got less weight than slower nginx_8006

======================================================================
FAIL: test_inherit (sched.test_per_group_lb.RedefineGlobalSched)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 321, in test_inherit
    self.check_lb(group, lb_type)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 303, in check_lb
    self.check_dynamic_lb(group, group_name)
  File "/root/tempesta-test/sched/test_per_group_lb.py", line 272, in check_dynamic_lb
    % (prev_name, name))
AssertionError: Faster server nginx_8005 got less weight than slower nginx_8006

======================================================================
FAIL: test (long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/long_body/test_response_wrong_length.py", line 225, in test
    self.generic_test_routine(self.config, [])
  File "/root/tempesta-test/testers/functional.py", line 168, in generic_test_routine
    self.tester.run()
  File "/root/tempesta-test/helpers/deproxy.py", line 952, in run
    self.check_expectations()
  File "/root/tempesta-test/helpers/deproxy.py", line 966, in check_expectations
    expected.msg if expected else ""))
AssertionError: Received message (response) does not suit expected one!

	Receieved:
<<<<<|
HTTP/1.1 502 Bad Gateway
date: Mon, 08 Mar 2021 00:24:00 GMT
content-length: 0
server: Tempesta FW/0.7.0
connection: close

|>>>>>
	Expected:
<<<<<|
HTTP/1.1 200 OK
Connection: keep-alive
Content-type: text/html
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Tempesta FW/0.7.0
Via: 1.1 tempesta_fw (Tempesta FW 0.7.0)
Date: Mon, 08 Mar 2021 00:24:00 GMT
transfer-encoding: chunked

0

|>>>>>


======================================================================
FAIL: test_big_body_to_chunked (msg_modification.tests_encode_to_chunked.MessageTransformations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 128, in test_big_body_to_chunked
    rec_resp = self.send_req(client)
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 63, in send_req
    self.assertEqual(curr_responses + 1, len(client.responses))
AssertionError: 1 != 0

======================================================================
FAIL: test_small_body_to_chunked (msg_modification.tests_encode_to_chunked.MessageTransformations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 99, in test_small_body_to_chunked
    rec_resp = self.send_req(client)
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 63, in send_req
    self.assertEqual(curr_responses + 1, len(client.responses))
AssertionError: 1 != 0

======================================================================
FAIL: test_transform_possible (msg_modification.tests_encode_to_chunked.MessageTransformations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 220, in test_transform_possible
    rec_resp = self.send_req(client)
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 63, in send_req
    self.assertEqual(curr_responses + 1, len(client.responses))
AssertionError: 1 != 0

======================================================================
FAIL: test_zero_body_to_chunked (msg_modification.tests_encode_to_chunked.MessageTransformations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 157, in test_zero_body_to_chunked
    rec_resp = self.send_req(client)
  File "/root/tempesta-test/msg_modification/tests_encode_to_chunked.py", line 63, in send_req
    self.assertEqual(curr_responses + 1, len(client.responses))
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 443 tests in 3398.912s

FAILED (failures=9, errors=10, skipped=17)
```

**Comment by krizhanovsky** [comment]
`Can't start Nginx` errors are invalid: I had wrong configuration for `aliases_interface` and `aliases_base_ip`.

**Comment by krizhanovsky** [comment]
I just rerun the test
```
./run_tests.py -n long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength
```
with the fixed config and with the 6th layer of verbosity:


```
----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------

	Run command 'echo "Start test: long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength.test" > /dev/kmsg' on host localhost with environment {}
test (long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength) ... 	Run command 'date +%s.%N' on host localhost with environment {}

	Init test case...
	Run command 'cat /root/tempesta/tempesta_fw/tempesta_fw.h | grep TFW_VERSION | awk -F '[\" ]' '{printf $3}'' on host localhost with environment {}
Starting 1 servers
	Deproxy: Server: Start on 127.0.0.1:8000.
	Starting TempestaFW on localhost
	Run command '/root/tempesta/scripts/tempesta.sh --start' on host localhost with environment {'TFW_CFG_PATH': u'/tmp/tempesta.conf'}
	Starting deproxy client
	Deproxy: Client: Connect to 127.0.0.1:80.
	Starting deproxy tester
	Starting completed
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: SrvConnection: New server connection.
	Deproxy: Client: Send request to Tempesta.
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: curl/7.53.1
Connection: keep-alive
Accept: */*


	Deproxy: SrvConnection: Receive request from Tempesta.
GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: curl/7.53.1
Connection: keep-alive
Accept: */*
X-Forwarded-For: 127.0.0.1
via: 1.1 tempesta_fw (Tempesta FW 0.7.0)


	Deproxy: SrvConnection: Send response to Tempesta.
HTTP/1.1 200 OK
Connection: keep-alive
Content-type: text/html
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Deproxy Server
Date: Thu, 11 Mar 2021 15:53:16 GMT


	Deproxy: SrvConnection: Close connection.
	Deproxy: Client: Receive response from Tempesta.
HTTP/1.1 502 Bad Gateway
date: Thu, 11 Mar 2021 15:53:17 GMT
content-length: 0
server: Tempesta FW/0.7.0
connection: close


FAIL
	Stop deproxy client
	Stopping TempestaFW on localhost
	Run command '/root/tempesta/scripts/tempesta.sh --stop' on host localhost with environment {}
	Stopping deproxy tester
	Deproxy: Server: Stop on 127.0.0.1:8000.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Deproxy: SrvConnection: Close connection.
	Run command 'journalctl -k -o cat --since=@1615477996.546927' on host localhost with environment {}
	Run command 'echo "End test:   long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength.test" > /dev/kmsg' on host localhost with environment {}

======================================================================
FAIL: test (long_body.test_response_wrong_length.ResponseMissingEmptyBodyLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta-test/long_body/test_response_wrong_length.py", line 225, in test
    self.generic_test_routine(self.config, [])
  File "/root/tempesta-test/testers/functional.py", line 168, in generic_test_routine
    self.tester.run()
  File "/root/tempesta-test/helpers/deproxy.py", line 952, in run
    self.check_expectations()
  File "/root/tempesta-test/helpers/deproxy.py", line 966, in check_expectations
    expected.msg if expected else ""))
AssertionError: Received message (response) does not suit expected one!

	Receieved:
<<<<<|
HTTP/1.1 502 Bad Gateway
date: Thu, 11 Mar 2021 15:53:17 GMT
content-length: 0
server: Tempesta FW/0.7.0
connection: close

|>>>>>
	Expected:
<<<<<|
HTTP/1.1 200 OK
Connection: keep-alive
Content-type: text/html
Last-Modified: Mon, 12 Dec 2016 13:59:39 GMT
Server: Tempesta FW/0.7.0
Via: 1.1 tempesta_fw (Tempesta FW 0.7.0)
Date: Thu, 11 Mar 2021 15:53:16 GMT
transfer-encoding: chunked

0

|>>>>>


----------------------------------------------------------------------
Ran 1 test in 1.278s

FAILED (failures=1)
```

**Comment by krizhanovsky** [comment]
Fixed in https://github.com/tempesta-tech/tempesta-test/pull/186 and https://github.com/tempesta-tech/tempesta/pull/1497
