### ISSUE TITLE
[Functional tests failure] HTTP scheduler functional test failure

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#701]
HTTP scheduler functional test is not working due to issue #698 

```
======================================================================
ERROR: test_scheduler (sched.test_http.HttpRules)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tempesta/tempesta_fw/t/functional/sched/test_http.py", line 111, in test_scheduler
    self.routine()
  File "/home/user/tempesta/tempesta_fw/t/functional/sched/test_http.py", line 94, in routine
    self.testers[0].loop()
  File "/home/user/tempesta/tempesta_fw/t/functional/helpers/deproxy.py", line 610, in loop
    poll_fun(min(self.timeout, timeout), map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 117, in readwrite
    obj.handle_error()
  File "/home/user/tempesta/tempesta_fw/t/functional/helpers/deproxy.py", line 451, in handle_error
    error.bug('\tDeproxy: Client: %s' % v)
  File "/home/user/tempesta/tempesta_fw/t/functional/helpers/error.py", line 28, in bug
    raise Error(msg)
Error: 	Deproxy: Client: [Errno 111] Connection refused
```

**Comment by ikoveshnikov** [comment]
Fixed in d25813da1bbd8665dee49b7c86e1d4b3fabeb5cd
