### ISSUE TITLE
regression.test_reboot.RebootUnderLoadTest dirty shutdown

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#932]
Running `# ./run_tests.py regression.test_reboot.RebootUnderLoadTest` throws many exceptions and leaves the system in inconsistent state: nginx is killed while Tempesta FW is running and trying to connect to Nginx.

```
# ./run_tests.py regression.test_reboot.RebootUnderLoadTest

----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------

test_cache (regression.test_reboot.RebootUnderLoadTest) ... FAIL
test_proxy (regression.test_reboot.RebootUnderLoadTest) ... FAIL

======================================================================
FAIL: test_cache (regression.test_reboot.RebootUnderLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 63, in test_cache
    self.reboot_routine(config)
  File "/root/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 52, in reboot_routine
    control.client_run_blocking(self.wrk)
  File "/root/tempesta/tempesta_fw/t/functional/helpers/control.py", line 216, in client_run_blocking
    error.assertTrue(client.parse_out(stdout, stderr))
  File "/root/tempesta/tempesta_fw/t/functional/helpers/control.py", line 168, in parse_out
    assert not m, sock_err_msg
AssertionError: Socket errors on wrk. Too many concurrent connections?

======================================================================
FAIL: test_proxy (regression.test_reboot.RebootUnderLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 58, in test_proxy
    self.reboot_routine(config)
  File "/root/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 52, in reboot_routine
    control.client_run_blocking(self.wrk)
  File "/root/tempesta/tempesta_fw/t/functional/helpers/control.py", line 216, in client_run_blocking
    error.assertTrue(client.parse_out(stdout, stderr))
  File "/root/tempesta/tempesta_fw/t/functional/helpers/control.py", line 168, in parse_out
    assert not m, sock_err_msg
AssertionError: Socket errors on wrk. Too many concurrent connections?

----------------------------------------------------------------------
Ran 2 tests in 225.671s

FAILED (failures=2)
```

```
# ps -waef|grep nginx
root      3129   834  0 23:13 pts/0    00:00:00 grep nginx
# dmesg | tail -20
[ 1033.378266] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.380056] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.382780] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.385054] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.386885] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.389408] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.392244] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.394005] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.394008] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1033.394042] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 300 tries, keep trying...
[ 1094.816340] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816434] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816454] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816519] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816551] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816711] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816731] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816763] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816764] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
[ 1094.816780] [tempesta] Warning: Cannot establish connection with ::6056:54c0:ffff:ffff in 360 tries, keep trying...
```

```
# cat tests_config.ini
[Client]
ip = 127.0.0.1
hostname = localhost
ab = ab
wrk = /root/wrk/wrk
workdir = /tmp/client

[Tempesta]
workdir = /root/tempesta
ip = 127.0.0.1
hostname = localhost
user = root
config = /tmp/tempesta.conf
port = 22

[Server]
workdir = /tmp/nginx
ip = 127.0.0.1
hostname = localhost
nginx = nginx
user = root
port = 22
resources = /var/www/html/
listen_interface = ens3

[General]
duration = 10
concurrent_connections = 10
verbose = 1
log_file = tests_log.log
```

**Comment by vladtcvs** [comment]
Can't reproduce this issue
