### ISSUE TITLE
[Tests] Reboot under load test misbehaviour

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#943]
Just caught on `regression.test_reboot.RebootUnderLoadNoTimeoutTest`:
```
[11641.640745] [tempesta] Initializing Tempesta FW kernel module...
[11641.671034] [tempesta] Registering new scheduler: hash
[11641.725841] [tempesta] Registering new scheduler: http
[11641.778882] [tempesta] Registering new scheduler: ratio
[11641.911174] [tempesta] Prepearing for the configuration processing.
[11641.914943] [tempesta] Configuration processing is completed.
[11641.931655] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff887cfc400000
[11642.158135] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=268435456 rec_size=0 base=ffff887cec400000
[11642.163104] [tempesta] Open listen socket on: 0.0.0.0
[11642.180040] [tempesta] modules are started
[11649.734128] [tempesta] Stopping all modules...
[11650.063143] [tdb] Close table 'cache0.tdb'
[11650.082234] [tdb] Close table 'filter0.tdb'
[11650.083905] [tempesta] modules are stopped
[11650.099554] [tempesta] New configuration is cleaned.
[11650.102110] [tempesta] Warning: Trying to stop an inactive system
[11650.117575] [tempesta] Prepearing for the configuration processing.
[11650.120829] [tempesta] Un-registering scheduler: hash
[11650.125356] [tempesta] Configuration processing is completed.
[11650.136201] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff887cfc400000
[11650.139081] [tempesta] Open listen socket on: 0.0.0.0
[11650.139742] ------------[ cut here ]------------
[11650.139744] kernel BUG at /home/user/tempesta/tempesta/tempesta_fw/sched/tfw_sched_http.c:579!
[11650.139745] invalid opcode: 0000 [#1] SMP
[11650.139777] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O-) tfw_sched_hash(O-) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) crct10dif_pclmul crc32_pclmul ghash_clmulni_intel binfmt_misc iTCO_wdt snd_hda_codec_generic iTCO_vendor_support ppdev snd_hda_intel virtio_balloon evdev snd_hda_codec snd_hda_core snd_hwdep snd_pcm pcspkr snd_timer sg virtio_console lpc_ich snd serio_raw soundcore mfd_core qxl ttm drm_kms_helper shpchp drm parport_pc parport button ip_tables x_tables autofs4 ext4 crc16 jbd2 crc32c_generic fscrypto ecb mbcache sr_mod cdrom crc32c_intel virtio_blk virtio_net aesni_intel aes_x86_64 glue_helper lrw gf128mul ablk_helper cryptd psmouse ahci libahci i2c_i801 i2c_smbus ehci_pci uhci_hcd ehci_hcd libata usbcore usb_common virtio_pci virtio_ring virtio sym53c8xx scsi_transport_spi
[11650.139779]  scsi_mod [last unloaded: tempesta_tls]
[11650.139782] CPU: 1 PID: 21250 Comm: rmmod Tainted: G           O    4.9.0-tempesta-amd64 #1 Debian 4.9.35-tfw5-1
[11650.139783] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.11.0-20171110_100015-anatol 04/01/2014
[11650.139784] task: ffff887cb7006580 task.stack: ffff9553807d4000
[11650.139789] RIP: 0010:[<ffffffffc07337ef>]  [<ffffffffc07337ef>] cleanup_module+0x2f/0x840 [tfw_sched_http]
[11650.139790] RSP: 0018:ffff9553807d7ee8  EFLAGS: 00010282
[11650.139791] RAX: ffffffffc07337c0 RBX: ffffffffc07351c0 RCX: 0000000000000000
[11650.139792] RDX: ffffffffc07354a0 RSI: ffffffffc07354c8 RDI: ffffffff97a52f80
[11650.139793] RBP: 000055e0386301f0 R08: 0000000000000070 R09: 0000000000000008
[11650.139794] R10: 0000000000000000 R11: ffff887cb7006580 R12: 0000000000000800
[11650.139795] R13: 0000000000000800 R14: 0000000000000000 R15: 000055e0386301f0
[11650.139797] FS:  00007f7bbb2ad700(0000) GS:ffff887cffd00000(0000) knlGS:0000000000000000
[11650.139798] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[11650.139799] CR2: 00007f7bbad30c40 CR3: 0000000032d0e000 CR4: 00000000003406e0
[11650.139802] Stack:
[11650.139805]  ffffffff96f0156c 656863735f776674 0000707474685f64 ffff9553807d7f58
[11650.139807]  0000000000000002 ffff887cb7006580 ffffffff96e0326c 00ff9553807d7f58
[11650.139809]  643cbe7e4f32d4e6 00007ffc8e1bb668 000055e0386301f0 00007ffc8e1bb830
[11650.139809] Call Trace:
[11650.139813]  [<ffffffff96f0156c>] ? SyS_delete_module+0x18c/0x260
[11650.139816]  [<ffffffff96e0326c>] ? exit_to_usermode_loop+0x8c/0xb0
[11650.139819]  [<ffffffff9740e1fb>] ? system_call_fast_compare_end+0xc/0x9b
[11650.139844] Code: 00 48 83 3d 33 1d 00 00 00 75 20 48 83 ec 08 48 c7 c7 60 51 73 c0 e8 d1 23 18 00 48 c7 c7 00 51 73 c0 48 83 c4 08 e9 e1 0c 18 00 <0f> 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[11650.139847] RIP  [<ffffffffc07337ef>] cleanup_module+0x2f/0x840 [tfw_sched_http]
[11650.139848]  RSP <ffff9553807d7ee8>
```
The next time i got test error without any crash:
```
======================================================================
ERROR: test_proxy (regression.test_reboot.RebootUnderLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 58, in test_proxy
    self.reboot_routine(config)
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/regression/test_reboot.py", line 46, in reboot_routine
    self.tempesta.start()
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/helpers/stateful.py", line 29, in start
    self.run_start()
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/helpers/control.py", line 289, in run_start
    err_msg=(self.err_msg % 'start'))
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/helpers/remote.py", line 155, in run_cmd
    error.bug(err_msg, stdout=stdout, stderr=stderr)
  File "/mnt/Storage/Projects/tempesta/tempesta/tempesta_fw/t/functional/helpers/remote.py", line 150, in run_cmd
    assert out_f.channel.recv_exit_status() == 0, "Return code is not 0."
Error: Can't start TempestaFW on 192.168.122.12 (AssertionError: Return code is not 0.)
stdout:
	Starting Tempesta...
	...enable RPS on lo
	...enable RPS on enp3s0
	...load Tempesta modules
	Loading Tempesta kernel modules...
	Loading module tempesta_db 
	Loading module tempesta_fw tfw_cfg_path=/home/user/tempesta/tempesta/etc/tempesta_fw.conf
	Loading module tfw_sched_hash 
	Loading module tfw_sched_http 
	Loading module tfw_sched_ratio 
	ERROR: cannot load tempesta scheduler module

stderr:
	insmod: ERROR: could not insert module /home/user/tempesta/tempesta/tempesta_fw/sched//tfw_sched_ratio.ko: File exists
```

**Comment by krizhanovsky** [comment]
Dublicate of #930: there is exactly the same Ooops.
