### ISSUE TITLE
mixed_requests.test_mixed.RarelyUsedRequests: HTTP client detected errors

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#945]
The issue appears after #936 fix: the test still fails:
```
# ./run_tests.py mixed_requests.test_mixed.RarelyUsedRequests
File tests_resume.json not found
Not resuming: File tests_resume.json not found

----------------------------------------------------------------------
Running functional tests...
----------------------------------------------------------------------

test (mixed_requests.test_mixed.RarelyUsedRequests) ... 
	Init test case...
	Starting Nginx on 127.0.0.1:8000
	Starting TempestaFW on localhost
	Running 1 HTTP clients on localhost
Running 10s test @ http://127.0.0.1/
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.67ms   22.67ms 122.82ms   84.67%
    Req/Sec   622.10    793.05     9.01k    89.25%
  49251 requests in 10.02s, 6.96MB read
  Socket errors: connect 0, read 8848, write 0, timeout 0
  Non-2xx or 3xx responses: 31472
Requests/sec:   4916.48
Transfer/sec:    711.45KB
 
WARNING! Socket errors on wrk. Too many concurrent connections?
	Client: errors: 40320, requests: 49251, rate: 4916
	Clients in total: errors: 40320, requests: 49251, rate: 4916
FAIL
	Stoping TempestaFW on localhost
	Stoping Nginx on 127.0.0.1:8000
	Removing Nginx config for 127.0.0.1:8000

======================================================================
FAIL: test (mixed_requests.test_mixed.RarelyUsedRequests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/tempesta/tempesta_fw/t/functional/mixed_requests/mixed_test.py", line 17, in test
    self.generic_test_routine(self.config)
  File "/root/tempesta/tempesta_fw/t/functional/testers/stress.py", line 171, in generic_test_routine
    self.assert_clients()
  File "/root/tempesta/tempesta_fw/t/functional/testers/stress.py", line 113, in assert_clients
    self.assertEqual(err, 0, msg='HTTP client detected errors')
AssertionError: HTTP client detected errors

----------------------------------------------------------------------
Ran 1 test in 11.003s

FAILED (failures=1)
```

The result is the same for the following patch  (I also tried to replace `OPTIONS` with `GET` or `PATCH` and the results are the same):
```diff
diff --git a/tempesta_fw/t/functional/wrk/mixed.lua b/tempesta_fw/t/functional/wrk/mixed.lua
index f68100a..7734276 100644
--- a/tempesta_fw/t/functional/wrk/mixed.lua
+++ b/tempesta_fw/t/functional/wrk/mixed.lua
@@ -3,14 +3,6 @@
 init = function(args)
    local r = {}
    r[1] = wrk.format("OPTIONS", "/")
-   r[2] = wrk.format("GET", "/")
-   r[3] = wrk.format("HEAD", "/")
-   r[4] = wrk.format("POST", "/")
-   r[5] = wrk.format("PUT", "/")
-   r[6] = wrk.format("PATCH", "/")
-   r[7] = wrk.format("DELETE", "/")
-   r[8] = wrk.format("TRACE", "/")
-   r[9] = wrk.format("CONNECT", "/")
    req = table.concat(r)
 end
```

I tried to execute OPTIONS request using curl and it works fine with Tempesta FW configured as a proxy:
```
# curl -v -X OPTIONS http://192.168.100.4:80/
*   Trying 192.168.100.4...
* TCP_NODELAY set
* Connected to 192.168.100.4 (192.168.100.4) port 80 (#0)
> OPTIONS / HTTP/1.1
> Host: 192.168.100.4
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 10 Mar 2018 18:59:06 GMT
< Allow: GET,HEAD,POST,OPTIONS,HEAD,HEAD
< Content-Length: 0
< Connection: 
< Content-Type: text/html
< Server: Tempesta FW/0.5.0
< Via: 1.1 tempesta_fw (Tempesta FW 0.5.0)
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.100.4 left intact
```

So it seems there is some problem with the wrk script. Also please make error message more developer friendly: `HTTP client detected errors` - what can I do with the error message and how to debug the problem? What errors exactly? Which requests produced the errors?

**Comment by krizhanovsky** [comment]
The initial test was run with options:
```
duration = 10
concurrent_connections = 10
```

If I run the test with `wrk/mixed.lua` as
```lua
-- example script demonstrating HTTP pipelining

init = function(args)
   local r = {}
   r[1] = wrk.format("GET", "/")
   req = table.concat(r)
end

request = function()
   return req
end
```
, then it fails. However, if I just reduce concurrency to one `concurrent_connections = 1` the test finishes successfully. Seems like the recent problem with 502 responses.

**Comment by vladtcvs** [comment]
I have 
```
[   69.115184] tempesta_tls: loading out-of-tree module taints kernel.
[   69.566813] [tdb] Start Tempesta DB
[   70.025001] [tempesta] Initializing Tempesta FW kernel module...
[   70.080781] [tempesta] Registering new scheduler: hash
[   70.136988] [tempesta] Registering new scheduler: http
[   70.372704] [tempesta] Registering new scheduler: ratio
[   70.474743] [tempesta] Prepearing for the configuration processing.
[   70.575323] [tempesta] Configuration processing is completed.
[   70.615574] [tdb] Opened table /opt/tempesta/db/filter.tdb: size=16777216 rec_size=20 base=ffff96b03c000000
[   70.705854] [tempesta] Open listen socket on: 0.0.0.0
[   70.709083] [tempesta] modules are started
[   71.003044] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x72('r>nginx/1.13.8</') data_len=43 off=0
[   71.006335] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   75.040761] net_ratelimit: 494 callbacks suppressed
[   75.069875] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=1033 off=0
[   75.135825] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   80.885117] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=1033 off=0
[   80.888139] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   81.000445] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=1033 off=0
[   81.007699] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   81.208898] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=1033 off=0
[   81.216517] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   81.358614] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=1033 off=0
[   81.725478] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   82.133022] [tempesta] Warning: Parser error: state=Resp_HttpVer input=0x63('center>nginx/1.1') data_len=48 off=0
[   82.499706] [tempesta] Warning: response dropped: processing error: ::ffff:7f00:1
[   82.534751] general protection fault: 0000 [#1] SMP DEBUG_PAGEALLOC
[   82.536114] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) fuse edac_mce_amd edac_core crct10dif_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper psmouse ablk_helper pcspkr ppdev cryptd sr_mod parport_pc cdrom e1000 parport sg button ac i2c_piix4 battery ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto mbcache serio_raw sd_mod
[   82.536114] CPU: 0 PID: 736 Comm: nginx Tainted: G           O    4.9.35-kdump+ #17
[   82.536114] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
[   82.536114] task: ffff96b00c9f72c0 task.stack: ffffa8ef00748000
[   82.536114] RIP: 0010:[<ffffffffc0447a49>]  [<ffffffffc0447a49>] validate_addr+0x9/0x20 [tempesta_fw]
[   82.536114] RSP: 0018:ffff96b03f803888  EFLAGS: 00010206
[   82.536114] RAX: ffff96b00b51f520 RBX: ffffffffc04832d8 RCX: 0000000000000000
[   82.536114] RDX: 0000000000000036 RSI: ffff96b03f8038b8 RDI: 6b6b6b6b6b6b6b93
[   82.536114] RBP: ffff96b03f803888 R08: ffffe4efc12f5ce0 R09: 0000000000000067
[   82.536114] R10: 00003ffffffff000 R11: 0000000000000000 R12: 0000000000000000
[   82.536114] R13: ffffffffc04832d8 R14: 0000000000000000 R15: ffff96b00bec0f00
[   82.536114] FS:  00007ff498fa4740(0000) GS:ffff96b03f800000(0000) knlGS:0000000000000000
[   82.536114] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   82.536114] CR2: 00007ff553635790 CR3: 000000004c9fa000 CR4: 00000000000406f0
[   82.536114] Stack:
[   82.536114]  ffff96b03f8038a8 ffffffffc0447dbc ffffffffc04832d8 0000000000000000
[   82.536114]  ffff96b03f803908 ffffffffc0451096 0000000000000000 0000000000000000
[   82.536114]  0000000000000000 0000000000000000 0000000000000000 0000000000000000
[   82.536114] Call Trace:
[   82.536114]  <IRQ> [   82.536114]  [<ffffffffc0447dbc>] tfw_addr_ntop+0xc/0x60 [tempesta_fw]
[   82.536114]  [<ffffffffc0451096>] tfw_http_cli_error_resp_and_log.part.32+0x56/0xa0 [tempesta_fw]
[   82.536114]  [<ffffffffc0453c84>] tfw_http_srv_error_resp_and_log+0xe4/0x180 [tempesta_fw]
[   82.536114]  [<ffffffffc0454766>] tfw_http_msg_process+0x556/0xbc0 [tempesta_fw]
[   82.536114]  [<ffffffffc0452dd8>] ? tfw_http_resp_cache+0xc8/0x180 [tempesta_fw]
[   82.536114]  [<ffffffffbca5f56d>] ? __alloc_skb+0x3d/0x200
[   82.536114]  [<ffffffffc045007f>] __gfsm_fsm_exec+0x4f/0x90 [tempesta_fw]
[   82.536114]  [<ffffffffc045029f>] tfw_gfsm_dispatch+0xf/0x20 [tempesta_fw]
[   82.536114]  [<ffffffffc044f7e9>] tfw_connection_recv+0x49/0x60 [tempesta_fw]
[   82.536114]  [<ffffffffc04738f3>] ss_tcp_process_data+0x1c3/0x490 [tempesta_fw]
[   82.536114]  [<ffffffffbcacbc6b>] ? tcp_ack+0xcbb/0x15b0
[   82.536114]  [<ffffffffc044f7e9>] ? tfw_connection_recv+0x49/0x60 [tempesta_fw]
[   82.536114]  [<ffffffffc0473f66>] ss_tcp_state_change+0x96/0x1c0 [tempesta_fw]
[   82.536114]  [<ffffffffbcacd018>] tcp_fin+0xe8/0x160
[   82.536114]  [<ffffffffbcacd66e>] tcp_data_queue+0x5de/0xd40
[   82.536114]  [<ffffffffbcacdffd>] tcp_rcv_established+0x22d/0x6f0
[   82.536114]  [<ffffffffbca8be2b>] ? sk_filter_trim_cap+0x2b/0x260
[   82.536114]  [<ffffffffbcad8a50>] tcp_v4_do_rcv+0x140/0x200
[   82.536114]  [<ffffffffbcada272>] tcp_v4_rcv+0x912/0xa10
[   82.536114]  [<ffffffffc043f858>] ? tdb_rec_get+0x38/0x80 [tempesta_db]
[   82.536114]  [<ffffffffbcab31bd>] ip_local_deliver_finish+0x9d/0x1d0
[   82.536114]  [<ffffffffbcab34aa>] ip_local_deliver+0x6a/0xe0
[   82.536114]  [<ffffffffbcaabd00>] ? nf_iterate+0x50/0x60
[   82.536114]  [<ffffffffbcab2e43>] ip_rcv_finish+0x113/0x3f0
[   82.536114]  [<ffffffffbcab37a6>] ip_rcv+0x286/0x3d0
[   82.536114]  [<ffffffffbcab2d30>] ? inet_del_offload+0x40/0x40
[   82.536114]  [<ffffffffbca72512>] __netif_receive_skb_core+0x4d2/0xa30
[   82.536114]  [<ffffffffbcad1e00>] ? tcp_write_xmit+0x300/0xef0
[   82.536114]  [<ffffffffc047e933>] ? tfw_wq_pop_ticket+0x83/0x750 [tempesta_fw]
[   82.536114]  [<ffffffffbca72a83>] __netif_receive_skb+0x13/0x60
[   82.536114]  [<ffffffffbca73a68>] process_backlog+0x88/0x120
[   82.536114]  [<ffffffffbca73252>] net_rx_action+0x202/0x2f0
[   82.536114]  [<ffffffffbc666f2d>] __do_softirq+0xed/0x200
[   82.536114]  [<ffffffffbcb739cc>] do_softirq_own_stack+0x1c/0x30
[   82.536114]  <EOI> [   82.536114]  [<ffffffffbc666ade>] do_softirq.part.16+0x2e/0x40
[   82.536114]  [<ffffffffbc666b63>] __local_bh_enable_ip+0x73/0x80
[   82.536114]  [<ffffffffbcab76be>] ip_finish_output2+0x17e/0x340
[   82.536114]  [<ffffffffbcab85a6>] ip_finish_output+0x126/0x1c0
[   82.536114]  [<ffffffffbcab9039>] ip_output+0x69/0xe0
[   82.536114]  [<ffffffffbca54873>] ? sock_sendmsg+0x33/0x40
[   82.536114]  [<ffffffffbcab87c0>] ip_local_out+0x30/0x40
[   82.536114]  [<ffffffffbcab8af5>] ip_queue_xmit+0x155/0x3a0
[   82.536114]  [<ffffffffbcad1683>] tcp_transmit_skb+0x4b3/0x930
[   82.536114]  [<ffffffffbcad1e61>] tcp_write_xmit+0x361/0xef0
[   82.536114]  [<ffffffffbcacf8e8>] ? tcp_established_options+0x28/0xc0
[   82.536114]  [<ffffffffbcad2a1c>] __tcp_push_pending_frames+0x2c/0xa0
[   82.536114]  [<ffffffffbcad45aa>] tcp_send_fin+0x6a/0x1a0
[   82.536114]  [<ffffffffbcac2517>] tcp_shutdown+0x47/0x50
[   82.536114]  [<ffffffffbcaee2a0>] inet_shutdown+0x70/0xf0
[   82.536114]  [<ffffffffbca55bff>] SyS_shutdown+0x7f/0x90
[   82.536114]  [<ffffffffbcb724e4>] entry_SYSCALL_64_fastpath+0x17/0x98
[   82.536114] Code: 99 e8 9c a4 21 fc 41 ba 00 50 00 00 88 56 07 31 c0 66 44 89 56 02 e9 76 fe ff ff 0f 1f 80 00 00 00 00 55 48 85 ff 48 89 e5 74 0e <0f> b7 07 83 e0 f7 66 83 f8 02 75 04 5d c3 0f 0b 0f 0b 0f 1f 44 
[   82.536114] RIP  [<ffffffffc0447a49>] validate_addr+0x9/0x20 [tempesta_fw]
[   82.536114]  RSP <ffff96b03f803888>
```
for this test

**Comment by vladtcvs** [comment]
During tests I have found problem with 504 errors - gateway timeout

**Comment by krizhanovsky** [comment]
https://github.com/tempesta-tech/tempesta/issues/945#issuecomment-372146176 is also due to too old kernel: the call trace is equal to the one from #936
